name: update

on:
  schedule:
    - cron: "10 22 * * *"
  push:
    branches:
      - main
    paths-ignore:
      - "**/README.md"
jobs:
  update:
    if: github.repository == 'mixool/shadowrocket-rules'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: update
        run: |
            wget -qO- https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/reject-list.txt | sed "s/^/DOMAIN-SUFFIX,&/" | sed "/DOMAIN-SUFFIX,regexp:.*/d" | sed "/^$/d" >./ruleset/reject.list
            wget -qO- https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/direct-list.txt | sed "s/^/DOMAIN-SUFFIX,&/" | sed "/DOMAIN-SUFFIX,regexp:.*/d" | sed "/^$/d" >./ruleset/direct.list
            wget -qO- https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/apple-cn.txt    | sed "s/^/DOMAIN-SUFFIX,&/" | sed "/DOMAIN-SUFFIX,regexp:.*/d" | sed "/^$/d" >./ruleset/apple-cn.list
            wget -qO- https://raw.githubusercontent.com/Loyalsoldier/v2ray-rules-dat/release/google-cn.txt   | sed "s/^/DOMAIN-SUFFIX,&/" | sed "/DOMAIN-SUFFIX,regexp:.*/d" | sed "/^$/d" >./ruleset/google-cn.list
            bash generate.sh allrocket >./allrocket.conf

      - name: push
        run: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git commit -am "update"
            git push -v --progress
